controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

#lucky_test:
#    path: /lucky-oooops
#    controller: App\Controller\LuckyController::test
#
#user_register:
#    path: /user/register
#    controller: App\Controller\UserController::registerAction
#
#user_forgotPassword:
#    path: /user/forgotPassword
#    controller: App\Controller\UserController::forgotPasswordAction
